import { Product, ProductReview } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Laptop Pro 15',
    description: 'High-performance laptop with 16GB RAM, 1TB NVMe SSD, and M3 Pro chipset.',
    price: 108549.17,
    category: 'electronics',
    stock: 100,
    rating: 4.9,
    image: '💻',
  },
  {
    id: 2,
    name: 'Wireless Ergonomic Mouse',
    description: 'Precision optical sensor with silent mechanical switches and Bluetooth 5.3.',
    price: 2504.17,
    category: 'electronics',
    stock: 100,
    rating: 4.6,
    image: '🖱️',
  },
  {
    id: 3,
    name: 'USB-C HyperHub 7-in-1',
    description: '4K HDMI 60Hz, 100W Power Delivery, SD Card reader, dual USB-A 3.2.',
    price: 4174.17,
    category: 'electronics',
    stock: 100,
    rating: 4.8,
    image: '🔌',
  },
  {
    id: 4,
    name: 'Mechanical RGB Keyboard',
    description: 'Hot-swappable custom tactile switches with aircraft-grade aluminum frame.',
    price: 7514.17,
    category: 'electronics',
    stock: 100,
    rating: 4.9,
    image: '⌨️',
  },
  {
    id: 5,
    name: 'Heavyweight Classic T-Shirt',
    description: '100% combed organic cotton, pre-shrunk heavyweight fabric.',
    price: 2086.67,
    category: 'clothing',
    stock: 100,
    rating: 4.7,
    image: '👕',
  },
  {
    id: 6,
    name: 'Vintage Wash Denim Jacket',
    description: 'Authentic 14oz selvedge denim jacket with custom brass hardware.',
    price: 6679.17,
    category: 'clothing',
    stock: 100,
    rating: 4.5,
    image: '🧥',
  },
  {
    id: 7,
    name: 'Carbon Pro Running Shoes',
    description: 'Ultra-responsive carbon fiber plate with breathable kinetic mesh.',
    price: 10019.17,
    category: 'clothing',
    stock: 100,
    rating: 4.8,
    image: '👟',
  },
  {
    id: 8,
    name: 'Python Crash Course (3rd Ed)',
    description: 'A hands-on, project-based introduction to modern programming.',
    price: 3339.17,
    category: 'books',
    stock: 100,
    rating: 5.0,
    image: '📘',
  },
  {
    id: 9,
    name: 'Clean Code Architecture',
    description: 'A handbook of agile software craftsmanship and robust design patterns.',
    price: 2921.67,
    category: 'books',
    stock: 100,
    rating: 4.9,
    image: '📕',
  },
  {
    id: 10,
    name: 'The Art of Cyber Strategy',
    description: 'Ancient tactical wisdom applied to modern threat modeling.',
    price: 1084.67,
    category: 'books',
    stock: 100,
    rating: 4.7,
    image: '📗',
  },
  {
    id: 11,
    name: 'Precision Programmable Brewer',
    description: '12-cup thermal carafe with PID temperature control and bloom timer.',
    price: 5844.17,
    category: 'home',
    stock: 100,
    rating: 4.4,
    image: '☕',
  },
  {
    id: 12,
    name: 'Minimalist LED Desk Lamp',
    description: 'Color temperature tunable 2700K-6500K with integrated 15W Qi charging pad.',
    price: 3756.67,
    category: 'home',
    stock: 100,
    rating: 4.8,
    image: '💡',
  },
];

export const INITIAL_REVIEWS: ProductReview[] = [
  {
    id: 1,
    product_id: 1,
    user_id: 2,
    username: 'user1',
    rating: 5,
    comment: 'Amazing laptop, compiles models in seconds. Incredible display!',
    created_at: '2026-10-02T10:14:22Z',
  },
  {
    id: 2,
    product_id: 2,
    user_id: 2,
    username: 'user1',
    rating: 4,
    comment: 'Ergonomics are top notch, slightly smaller than anticipated.',
    created_at: '2026-10-02T11:32:05Z',
  },
  {
    id: 3,
    product_id: 5,
    user_id: 3,
    username: 'user2',
    rating: 5,
    comment: 'Fits true to size, material feels durable after multiple washes.',
    created_at: '2026-10-02T14:48:19Z',
  },
  {
    id: 4,
    product_id: 8,
    user_id: 3,
    username: 'user2',
    rating: 5,
    comment: 'Clear explanations and realistic exercises. Highly recommended.',
    created_at: '2026-10-03T09:12:44Z',
  },
];
